name: sheet_loader_localization
description: Download an CSV file and generates the localization keys from an online Google Sheet.
version: 1.0.0
homepage: https://github.com/Hoang-Nguyenn
repository: https://github.com/Hoang-Nguyenn/sheet_loader_localization
issue_tracker: https://github.com/Hoang-Nguyenn/sheet_loader_localization/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.4
  build_config: ^1.2.0
  source_gen: ^4.2.0
  http: ^1.6.0
  path: ^1.9.1
  csv: ^6.0.0
  intl: ^0.20.2
  analyzer: ^10.0.1
  file: ^7.0.1
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
